import { DataType } from "@microsoft/fast-tooling";
import { WebComponentDefinition } from "@microsoft/fast-tooling/dist/esm/data-utilities/web-component";
import { Direction } from "@microsoft/fast-web-utilities";
import { fastDesignSystemDefaults } from "../fast-design-system";

export const fastDesignSystemProviderDefinition: WebComponentDefinition = {
    version: 1,
    tags: [
        {
            name: "fast-design-system-provider",
            description: "The FAST design system provider element",
            attributes: [
                {
                    name: "use-defaults",
                    title: "Use defaults",
                    description: "Use default design system values",
                    type: DataType.boolean,
                    default: true,
                    required: false,
                },
                {
                    name: "no-paint",
                    title: "No paint",
                    description: "Do not paint the background",
                    type: DataType.boolean,
                    default: false,
                    required: false,
                },
                {
                    name: "background-color",
                    title: "Background color",
                    description: "The background color",
                    type: DataType.string,
                    default: fastDesignSystemDefaults.backgroundColor,
                    required: false,
                },
                {
                    name: "accent-base-color",
                    title: "Accent base color",
                    description: "The accent palette base color",
                    type: DataType.string,
                    default: fastDesignSystemDefaults.accentBaseColor,
                    required: false,
                },
                {
                    name: "density",
                    title: "Density",
                    description: "The density offset",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.density,
                    required: false,
                },
                {
                    name: "design-unit",
                    title: "Design unit",
                    description: "UI dimension base unit",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.designUnit,
                    required: false,
                },
                {
                    name: "direction",
                    title: "Direction",
                    description: "Support localized styles",
                    type: DataType.string,
                    values: [Direction.ltr, Direction.rtl],
                    default: fastDesignSystemDefaults.direction,
                    required: false,
                },
                {
                    name: "base-height-multiplier",
                    title: "Base height multiplier",
                    description: "Height multiplier at base density",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.baseHeightMultiplier,
                    required: false,
                },
                {
                    name: "base-horizontal-spacing-multiplier",
                    title: "Base horizontal spacing multiplier",
                    description: "Horizontal spacing multiplier at the base density",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.baseHorizontalSpacingMultiplier,
                    required: false,
                },
                {
                    name: "corner-radius",
                    title: "Corner radius",
                    description: "The corner radius value for elements",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.cornerRadius,
                    required: false,
                },
                {
                    name: "outline-width",
                    title: "Outline width",
                    description: "The width of outline strokes",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.outlineWidth,
                    required: false,
                },
                {
                    name: "focus-outline-width",
                    title: "Focus outline width",
                    description: "The width of focus outline strokes",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.focusOutlineWidth,
                    required: false,
                },
                {
                    name: "disabled-opacity",
                    title: "Disabled opacity",
                    description: "The disabled opacity for elements",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.disabledOpacity,
                    required: false,
                },
                {
                    name: "type-ramp-minus-2-font-size",
                    title: "Font size (-2)",
                    type: DataType.string,
                    default: fastDesignSystemDefaults.typeRampMinus2FontSize,
                    required: false,
                },
                {
                    name: "type-ramp-minus-2-line-height",
                    title: "Line height (-2)",
                    type: DataType.string,
                    default: fastDesignSystemDefaults.typeRampMinus2LineHeight,
                    required: false,
                },
                {
                    name: "type-ramp-minus-1-font-size",
                    title: "Font size (-1)",
                    type: DataType.string,
                    default: fastDesignSystemDefaults.typeRampMinus1FontSize,
                    required: false,
                },
                {
                    name: "type-ramp-minus-1-line-height",
                    title: "Line height (-1)",
                    type: DataType.string,
                    default: fastDesignSystemDefaults.typeRampMinus1LineHeight,
                    required: false,
                },
                {
                    name: "type-ramp-base-font-size",
                    title: "Font size (base)",
                    type: DataType.string,
                    default: fastDesignSystemDefaults.typeRampBaseFontSize,
                    required: false,
                },
                {
                    name: "type-ramp-base-line-height",
                    title: "Line height (base)",
                    type: DataType.string,
                    default: fastDesignSystemDefaults.typeRampBaseLineHeight,
                    required: false,
                },
                {
                    name: "type-ramp-plus-1-font-size",
                    title: "Font size (+1)",
                    type: DataType.string,
                    default: fastDesignSystemDefaults.typeRampPlus1FontSize,
                    required: false,
                },
                {
                    name: "type-ramp-plus-1-line-height",
                    title: "Line height (+1)",
                    type: DataType.string,
                    default: fastDesignSystemDefaults.typeRampPlus1LineHeight,
                    required: false,
                },
                {
                    name: "type-ramp-plus-2-font-size",
                    title: "Font size (+2)",
                    type: DataType.string,
                    default: fastDesignSystemDefaults.typeRampPlus2FontSize,
                    required: false,
                },
                {
                    name: "type-ramp-plus-2-line-height",
                    title: "Line height (+2)",
                    type: DataType.string,
                    default: fastDesignSystemDefaults.typeRampPlus2LineHeight,
                    required: false,
                },
                {
                    name: "type-ramp-plus-3-font-size",
                    title: "Font size (+3)",
                    type: DataType.string,
                    default: fastDesignSystemDefaults.typeRampPlus3FontSize,
                    required: false,
                },
                {
                    name: "type-ramp-plus-3-line-height",
                    title: "Line height (+3)",
                    type: DataType.string,
                    default: fastDesignSystemDefaults.typeRampPlus3LineHeight,
                    required: false,
                },
                {
                    name: "type-ramp-plus-4-font-size",
                    title: "Font size (+4)",
                    type: DataType.string,
                    default: fastDesignSystemDefaults.typeRampPlus4FontSize,
                    required: false,
                },
                {
                    name: "type-ramp-plus-4-line-height",
                    title: "Line height (+4)",
                    type: DataType.string,
                    default: fastDesignSystemDefaults.typeRampPlus4LineHeight,
                    required: false,
                },
                {
                    name: "type-ramp-plus-5-font-size",
                    title: "Font size (+5)",
                    type: DataType.string,
                    default: fastDesignSystemDefaults.typeRampPlus5FontSize,
                    required: false,
                },
                {
                    name: "type-ramp-plus-5-line-height",
                    title: "Line height (+5)",
                    type: DataType.string,
                    default: fastDesignSystemDefaults.typeRampPlus5LineHeight,
                    required: false,
                },
                {
                    name: "type-ramp-plus-6-font-size",
                    title: "Font size (+6)",
                    type: DataType.string,
                    default: fastDesignSystemDefaults.typeRampPlus6FontSize,
                    required: false,
                },
                {
                    name: "type-ramp-plus-6-line-height",
                    title: "Line height (+6)",
                    type: DataType.string,
                    default: fastDesignSystemDefaults.typeRampPlus6LineHeight,
                    required: false,
                },
                {
                    name: "accent-fill-rest-delta",
                    title: "Accent fill delta (rest)",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.accentFillRestDelta,
                    required: false,
                },
                {
                    name: "accent-fill-hover-delta",
                    title: "Accent fill delta (hover)",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.accentFillHoverDelta,
                    required: false,
                },
                {
                    name: "accent-fill-active-delta",
                    title: "Accent fill delta (active)",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.accentFillActiveDelta,
                    required: false,
                },
                {
                    name: "accent-fill-focus-delta",
                    title: "Accent fill delta (focus)",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.accentFillFocusDelta,
                    required: false,
                },
                {
                    name: "accent-fill-selected-delta",
                    title: "Accent fill delta (selected)",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.accentFillSelectedDelta,
                    required: false,
                },
                {
                    name: "accent-foreground-rest-delta",
                    title: "Accent foreground delta (rest)",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.accentForegroundRestDelta,
                    required: false,
                },
                {
                    name: "accent-foreground-hover-delta",
                    title: "Accent foreground delta (hover)",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.accentForegroundHoverDelta,
                    required: false,
                },
                {
                    name: "accent-foreground-active-delta",
                    title: "Accent foreground delta (active)",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.accentForegroundActiveDelta,
                    required: false,
                },
                {
                    name: "accent-foreground-focus-delta",
                    title: "Accent foreground delta (focus)",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.accentForegroundFocusDelta,
                    required: false,
                },
                {
                    name: "neutral-fill-rest-delta",
                    title: "Neutral fill delta (rest)",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.accentFillRestDelta,
                    required: false,
                },
                {
                    name: "neutral-fill-hover-delta",
                    title: "Neutral fill delta (hover)",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.neutralFillHoverDelta,
                    required: false,
                },
                {
                    name: "neutral-fill-active-delta",
                    title: "Neutral fill delta (active)",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.neutralFillActiveDelta,
                    required: false,
                },
                {
                    name: "neutral-fill-focus-delta",
                    title: "Neutral fill delta (focus)",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.neutralFillFocusDelta,
                    required: false,
                },
                {
                    name: "neutral-fill-selected-delta",
                    title: "Neutral fill delta (selected)",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.neutralFillSelectedDelta,
                    required: false,
                },
                {
                    name: "neutral-fill-input-rest-delta",
                    title: "Neutral fill input delta (rest)",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.neutralFillInputRestDelta,
                    required: false,
                },
                {
                    name: "neutral-fill-input-hover-delta",
                    title: "Neutral fill input delta (hover)",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.neutralFillInputHoverDelta,
                    required: false,
                },
                {
                    name: "neutral-fill-input-active-delta",
                    title: "Neutral fill input delta (active)",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.neutralFillInputActiveDelta,
                    required: false,
                },
                {
                    name: "neutral-fill-input-focus-delta",
                    title: "Neutral fill input delta (focus)",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.neutralFillInputFocusDelta,
                    required: false,
                },
                {
                    name: "neutral-fill-input-selected-delta",
                    title: "Neutral fill input delta (selected)",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.neutralFillInputSelectedDelta,
                    required: false,
                },
                {
                    name: "neutral-fill-stealth-rest-delta",
                    title: "Neutral fill stealth delta (rest)",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.neutralFillStealthRestDelta,
                    required: false,
                },
                {
                    name: "neutral-fill-stealth-hover-delta",
                    title: "Neutral fill stealth delta (hover)",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.neutralFillStealthHoverDelta,
                    required: false,
                },
                {
                    name: "neutral-fill-stealth-active-delta",
                    title: "Neutral fill stealth delta (active)",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.neutralFillStealthActiveDelta,
                    required: false,
                },
                {
                    name: "neutral-fill-stealth-focus-delta",
                    title: "Neutral fill stealth delta (focus)",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.neutralFillStealthFocusDelta,
                    required: false,
                },
                {
                    name: "neutral-fill-stealth-selected-delta",
                    title: "Neutral fill stealth delta (selected)",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.neutralFillStealthSelectedDelta,
                    required: false,
                },
                {
                    name: "neutral-fill-toggle-hover-delta",
                    title: "Neutral fill toggle delta (hover)",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.neutralFillToggleHoverDelta,
                    required: false,
                },
                {
                    name: "neutral-fill-toggle-active-delta",
                    title: "Neutral fill toggle delta (active)",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.neutralFillToggleActiveDelta,
                    required: false,
                },
                {
                    name: "neutral-fill-toggle-focus-delta",
                    title: "Neutral fill toggle delta (focus)",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.neutralFillToggleFocusDelta,
                    required: false,
                },
                {
                    name: "base-layer-luminance",
                    title: "Base layer luminance",
                    description:
                        "When set to a number between 0 and 1, this values controls the output of layer and card recipes",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.baseLayerLuminance,
                    required: false,
                },
                {
                    name: "neutral-fill-card-delta",
                    title: "Card background delta",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.neutralFillCardDelta,
                    required: false,
                },
                {
                    name: "neutral-foreground-hover-delta",
                    title: "Neutral foreground delta (hover)",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.neutralForegroundHoverDelta,
                    required: false,
                },
                {
                    name: "neutral-foreground-active-delta",
                    title: "Neutral foreground delta (active)",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.neutralForegroundActiveDelta,
                    required: false,
                },
                {
                    name: "neutral-foreground-focus-delta",
                    title: "Neutral foreground delta (focus)",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.neutralForegroundFocusDelta,
                    required: false,
                },
                {
                    name: "neutral-divider-rest-delta",
                    title: "Neutral divider delta",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.neutralDividerRestDelta,
                    required: false,
                },
                {
                    name: "neutral-outline-rest-delta",
                    title: "Neutral outline delta (rest)",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.neutralOutlineRestDelta,
                    required: false,
                },
                {
                    name: "neutral-outline-hover-delta",
                    title: "Neutral outline delta (hover)",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.neutralOutlineHoverDelta,
                    required: false,
                },
                {
                    name: "neutral-outline-active-delta",
                    title: "Neutral outline delta (active)",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.neutralOutlineActiveDelta,
                    required: false,
                },
                {
                    name: "neutral-outline-focus-delta",
                    title: "Neutral outline delta (focus)",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.neutralOutlineFocusDelta,
                    required: false,
                },
                {
                    name: "neutral-contrast-fill-rest-delta",
                    title: "Neutral contrast fill delta (rest)",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.neutralContrastFillRestDelta,
                    required: false,
                },
                {
                    name: "neutral-contrast-fill-hover-delta",
                    title: "Neutral contrast fill delta (hover)",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.neutralContrastFillHoverDelta,
                    required: false,
                },
                {
                    name: "neutral-contrast-fill-active-delta",
                    title: "Neutral contrast fill delta (active)",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.neutralContrastFillActiveDelta,
                    required: false,
                },
                {
                    name: "neutral-contrast-fill-focus-delta",
                    title: "Neutral contrast fill delta (focus)",
                    type: DataType.number,
                    default: fastDesignSystemDefaults.neutralContrastFillFocusDelta,
                    required: false,
                },
            ],
            slots: [
                {
                    name: "",
                    title: "Default slot",
                },
            ],
        },
    ],
};
