import { FoundationElement } from "@microsoft/fast-foundation";
import { WebComponentDefinition } from "../../data-utilities/web-component";
import { MessageSystem } from "../../message-system";
export declare const HTMLRenderOriginatorId = "fast-tooling::html-renderer";
export declare class HTMLRender extends FoundationElement {
    private layerActivityId;
    private dataDictionary;
    private schemaDictionary;
    private messageOriginatorId;
    private dataDictionaryAttr;
    private tabCounter;
    private currentElement;
    private activeDictionaryId;
    private renderLayers;
    interactiveMode: boolean;
    markup: HTMLElement;
    markupDefinitions: WebComponentDefinition[];
    layers: HTMLSlotElement;
    private layersChanged;
    messageSystem: MessageSystem;
    private messageSystemChanged;
    private selectTimeout;
    private handleMessageSystem;
    private selectActiveDictionaryId;
    private updateLayers;
    private layerCallback;
    private getTargetElementFromMouseEvent;
    hoverHandler(e: MouseEvent): boolean;
    blurHandler(e: MouseEvent): boolean;
    private selectElement;
    private clearElement;
    clickHandler(e: MouseEvent): boolean;
    dblClickHandler(e: MouseEvent): boolean;
    keyUpHandler(e: KeyboardEvent): boolean;
    keyDownHandler(e: KeyboardEvent): boolean;
    containerClickHandler(e: MouseEvent): boolean;
    private renderHtmlResolver;
    renderMarkup(): void;
    private isHtmlRenderLayer;
}
