pulls:
  # Number of days of inactivity before an issue or pull request becomes stale.
  daysUntilStale: 5

  # Number of days of inactivity before a stale issue or pull request is closed.
  # Set to false to disable. If disabled, issues still need to be closed manually but remain marked as stale.
  daysUntilClose: 7

  # Comment to post when marking as stale. Set to `false` to disable.
  markComment: >
    This pull request has been automatically marked as stale because it has not had
    recent activity. It will be closed if no further activity occurs. Thank you
    for your contributions.

  # Limit the number of actions per hour, from 1-30. The default is 30.
  limitPerRun: 5
  
  # Label to use when marking a pull request as stale.
  staleLabel: "reason : stale"

  # Comment to post when removing the stale label.
  # unmarkComment: >
  #   Your comment here.

  # Comment to post when closing a stale issue or pull request.
  # closeComment: >
  #   Your comment here.

issues:
  # Number of days of inactivity before an issue or pull request becomes stale.
  daysUntilStale: 90

  # Number of days of inactivity before a stale issue or pull request is closed.
  # Set to false to disable. If disabled, issues still need to be closed manually but remain marked as stale.
  daysUntilClose: 10

  # Comment to post when marking as stale. Set to `false` to disable.
  markComment: >
    This issue has been automatically marked as stale because it has not had
    recent activity. It will be closed if no further activity occurs. Thank you
    for your contributions.

  # Issues or pull requests with these labels will never be considered stale. Set to `[]` to disable.
  exemptLabels:
    - "issue : task"
    - "discuss : feature request"
    - "[Status] Maybe Later"

  # Label to use when marking as stale.
  staleLabel: "reason : stale"

  # Limit the number of actions per hour, from 1-30. The default is 30.
  limitPerRun: 25