export interface ExampleComponent {
    schema: any;
    data?: any;
}
export declare const category: ExampleComponent;
export declare const customControl: ExampleComponent;
export declare const controlPluginCssWithOverrides: ExampleComponent;
export declare const controlPluginCss: ExampleComponent;
export declare const textField: ExampleComponent;
export declare const text: ExampleComponent;
export declare const numberField: ExampleComponent;
export declare const checkbox: ExampleComponent;
export declare const anyOf: ExampleComponent;
export declare const oneOf: ExampleComponent;
export declare const nestedOneOf: ExampleComponent;
export declare const mergedOneOf: ExampleComponent;
export declare const objects: ExampleComponent;
export declare const arrays: ExampleComponent;
export declare const oneOfArrays: ExampleComponent;
export declare const children: ExampleComponent;
export declare const generalExample: ExampleComponent;
export declare const badge: ExampleComponent;
export declare const constKeyword: ExampleComponent;
export declare const invalidData: ExampleComponent;
export declare const defaults: ExampleComponent;
export declare const nullKeyword: ExampleComponent;
export declare const allControlTypes: ExampleComponent;
export declare const dictionary: ExampleComponent;
export declare const tooltip: ExampleComponent;
export declare const disabled: ExampleComponent;
