module.exports = {
    docs: [
        {
            type: "doc",
            id: "introduction",
        },
        {
            type: "category",
            label: "Using FAST Components",
            items: [
                "components/getting-started",
                {
                    type: "category",
                    label: "Components",
                    items: [
                        "components/accordion",
                        "components/anchor",
                        "components/badge",
                        "components/button",
                        "components/card",
                        "components/checkbox",
                        "components/design-system-provider",
                        "components/dialog",
                        "components/divider",
                        "components/flipper",
                        "components/menu",
                        "components/menu-item",
                        "components/progress",
                        "components/radio",
                        "components/radio-group",
                        "components/slider",
                        "components/slider-label",
                        "components/switch",
                        "components/tabs",
                        "components/text-area",
                        "components/text-field",
                        "components/tree-view",
                    ],
                },
                {
                    type: "category",
                    label: "Design",
                    items: [
                        "design/introduction",
                        "design/design-system",
                        "design/type-ramp",
                        "design/color",
                        "design/localization",
                        "design/match-media-stylesheets",
                    ],
                },
            ],
        },
        {
            type: "category",
            label: "Using FAST Element",
            items: [
                "fast-element/getting-started",
                "fast-element/defining-elements",
                "fast-element/declaring-templates",
                "fast-element/using-directives",
                "fast-element/observables-and-state",
                "fast-element/working-with-shadow-dom",
                "fast-element/leveraging-css",
                "fast-element/next-steps",
            ],
        },
        {
            type: "category",
            label: "Working with Design Systems",
            items: [
                "design-systems/overview",
                "design-systems/fast-frame",
                "design-systems/using-the-design-system",
                "design-systems/creating-a-design-system",
            ],
        },
        {
            type: "category",
            label: "Tools",
            items: ["tools/component-explorer", "tools/vscode"],
        },
        {
            type: "category",
            label: "Integrations",
            items: [
                "integrations/introduction",
                "integrations/angular",
                "integrations/aspnet",
                "integrations/aurelia",
                "integrations/blazor",
                "integrations/react",
                "integrations/vue",
                "integrations/webpack",
            ],
        },
        {
            type: "category",
            label: "API Reference",
            items: [
                "api/fast-animation",
                "api/fast-colors",
                "api/fast-components",
                "api/fast-element",
                "api/fast-foundation",
            ],
        },
        {
            type: "category",
            label: "Community Contribution",
            items: [
                "community/join",
                "community/code-of-conduct",
                "community/contributor-guide",
                "community/writing-documentation",
            ],
        },
        {
            type: "category",
            label: "Resources",
            items: [
                "resources/license",
                "resources/security",
                "resources/browser-support",
                "resources/acknowledgements",
                "resources/glossary",
                "resources/faq",
            ],
        },
    ],
};
