import { expect, test } from "@playwright/test";
import type { HydrationMarkersV2Element } from "./main.js";

test.describe("FAST Element 2.x hydration markers", () => {
    test("hydrates output generated by fast-build with markers_v2", async ({ page }) => {
        const hydrationCompleted = page.waitForFunction(
            () => (window as any).hydrationCompleted === true,
        );
        await page.goto("/fixtures/ecosystem/hydration-markers-v2/");
        await hydrationCompleted;

        const rawFixtureHtml = await page.request
            .get("/fixtures/ecosystem/hydration-markers-v2/")
            .then(response => response.text());

        expect(rawFixtureHtml).toContain("fe-b$$start$$3$$fast-build$$fe-b");
        expect(rawFixtureHtml).toContain("fe-repeat$$start$$0$$fe-repeat");
        expect(rawFixtureHtml).toContain("data-fe-b-0");
        expect(rawFixtureHtml).toContain("data-fe-c-1-2");

        const element = page.locator("hydration-markers-v2-element");
        const input = element.locator("input");
        const button = element.locator("button");
        const items = element.locator("span");

        await expect(input).toHaveAttribute("data-server-node", "input");
        await expect(input).not.toHaveAttribute("data-fe-b-0", "");
        await expect(button).not.toHaveAttribute("data-fe-c-1-2", "");
        await expect(items).toHaveText(["one", "two"]);

        await element.evaluate((node: HydrationMarkersV2Element) => {
            node.disabled = true;
        });
        await expect(button).toBeDisabled();
        await element.evaluate((node: HydrationMarkersV2Element) => {
            node.disabled = false;
        });
        await expect(button).toBeEnabled();

        await button.click();
        expect(
            await element.evaluate((node: HydrationMarkersV2Element) => node.count),
        ).toBe(1);

        await element.evaluate((node: HydrationMarkersV2Element) => {
            node.items = ["three"];
        });
        await expect(items).toHaveText(["three"]);
        expect(
            await element.evaluate(
                (node: HydrationMarkersV2Element) =>
                    node.input === node.shadowRoot!.querySelector("input"),
            ),
        ).toBe(true);
    });
});
