/**
 * Optional SSR rendering backend powered by `@microsoft/fast-build`'s
 * WASM renderer. When available, this can be used instead of (or
 * alongside) Vite's `ssrLoadModule` for faster, production-closer SSR
 * fixture generation.
 *
 * Usage from a component's `entry-server.ts`:
 *
 * ```ts
 * import { createWasmRenderer } from "@microsoft/fast-test-harness/ssr/wasm-renderer.js";
 *
 * const renderer = createWasmRenderer({
 *     templates: "./src/*.html",
 *     cwd: import.meta.dirname,
 * });
 *
 * export function render(queryObj) {
 *     return renderer.render(queryObj);
 * }
 * ```
 */

import { readdirSync, readFileSync, statSync } from "node:fs";
import { createRequire } from "node:module";
import { join, resolve } from "node:path";

const require = createRequire(import.meta.url);

interface WasmModule {
    parse_f_templates(html: string): string;
    render_entry_with_templates(entry: string, templates: string, state: string): string;
    render(html: string, state: string): string;
}

interface WasmRendererOptions {
    /**
     * Glob pattern(s) or file paths to scan for `<f-template>` elements.
     * Comma-separated patterns are supported.
     */
    templates?: string;

    /**
     * Working directory for resolving template paths.
     * @default process.cwd()
     */
    cwd?: string;
}

interface RenderResult {
    /** Rendered fixture HTML to inject into the page. */
    fixture: string;
    /** Collected `<f-template>` markup to inject into the page. */
    template: string;
    /** Preload link tags (empty string for WASM renderer). */
    preloadLinks: string;
}

/**
 * Attempt to load the `@microsoft/fast-build` WASM module. Returns
 * `null` if the package isn't installed.
 */
function loadWasm(): WasmModule | null {
    try {
        // The WASM bindings are a CJS module generated by wasm-pack.
        const wasmPath = require.resolve(
            "@microsoft/fast-build/wasm/microsoft_fast_build.js",
        );
        return require(wasmPath) as WasmModule;
    } catch {
        return null;
    }
}

/**
 * Recursively collect all `.html` files under `dir`.
 */
function walkHtmlFiles(dir: string, results: string[] = []): string[] {
    let entries: string[];
    try {
        entries = readdirSync(dir);
    } catch {
        return results;
    }

    for (const name of entries) {
        const fullPath = join(dir, name);
        try {
            const stat = statSync(fullPath);
            if (stat.isDirectory()) {
                walkHtmlFiles(fullPath, results);
            } else if (stat.isFile() && name.endsWith(".html")) {
                results.push(fullPath);
            }
        } catch {
            // skip inaccessible entries
        }
    }

    return results;
}

/**
 * Parse `<f-template>` elements from an HTML file using the WASM parser.
 */
function parseFTemplates(
    html: string,
    wasm: WasmModule,
): Array<{ name: string; content: string }> {
    const parsed: Array<{ name: string | null; content: string }> = JSON.parse(
        wasm.parse_f_templates(html),
    );

    return parsed.filter((t): t is { name: string; content: string } => t.name !== null);
}

/**
 * Build a fixture element from query parameters (mirrors the logic in
 * `renderFixture` from `ssr/render.ts`).
 */
function buildFixtureHtml(queryObj: Record<string, string>): string {
    if ("html" in queryObj) {
        return String(queryObj.html);
    }

    if (!queryObj.tagName) {
        return "";
    }

    const tagName = String(queryObj.tagName);
    let attributes: Record<string, unknown> = {};

    if (queryObj.attributes) {
        try {
            attributes =
                typeof queryObj.attributes === "string"
                    ? JSON.parse(queryObj.attributes)
                    : queryObj.attributes;
        } catch {
            // ignore invalid JSON
        }
    }

    const innerHTML = queryObj.innerHTML ? String(queryObj.innerHTML) : "";

    const attributesString = Object.entries(attributes)
        .map(([key, value]) =>
            value === true ? key : `${key}="${String(value).replace(/"/g, "")}"`,
        )
        .join(" ");

    return `<${tagName}${attributesString ? ` ${attributesString}` : ""}>${innerHTML}</${tagName}>`;
}

/**
 * Creates a WASM-backed renderer for SSR test fixtures.
 *
 * @returns The renderer, or `null` if `@microsoft/fast-build` is not
 *   available.
 */
export function createWasmRenderer(options: WasmRendererOptions = {}): {
    render: (queryObj: Record<string, string>) => RenderResult;
} | null {
    const wasm = loadWasm();
    if (!wasm) {
        return null;
    }

    const cwd = options.cwd ?? process.cwd();

    // Collect templates from the specified patterns.
    const templatesMap: Record<string, string> = {};

    if (options.templates) {
        const patterns = options.templates.split(",").map(p => p.trim());

        for (const pattern of patterns) {
            const resolvedPath = resolve(cwd, pattern);

            // If it's a direct file path (no globs), read it directly.
            try {
                if (statSync(resolvedPath).isFile()) {
                    const html = readFileSync(resolvedPath, "utf8");
                    for (const { name, content } of parseFTemplates(html, wasm)) {
                        templatesMap[name] = content;
                    }
                    continue;
                }
            } catch {
                // Not a direct file — fall through to directory scan.
            }

            // Directory-based scan: walk and collect.
            const dir = resolve(cwd, pattern.replace(/\/\*.*$/, ""));
            const files = walkHtmlFiles(dir);
            for (const file of files) {
                const html = readFileSync(file, "utf8");
                for (const { name, content } of parseFTemplates(html, wasm)) {
                    templatesMap[name] = content;
                }
            }
        }
    }

    const templateEntries = Object.entries(templatesMap)
        .map(([name, content]) => `<f-template name="${name}">${content}</f-template>`)
        .join("\n");

    return {
        render(queryObj: Record<string, string>): RenderResult {
            const fixtureHtml = buildFixtureHtml(queryObj);

            // Build a minimal entry document for the WASM renderer.
            const entryHtml = `<!doctype html><html><body>${fixtureHtml}</body></html>`;

            // Build state from attributes + innerHTML.
            const state: Record<string, unknown> = {};
            if (queryObj.attributes) {
                try {
                    Object.assign(
                        state,
                        typeof queryObj.attributes === "string"
                            ? JSON.parse(queryObj.attributes)
                            : queryObj.attributes,
                    );
                } catch {
                    // ignore
                }
            }

            let rendered: string;
            if (Object.keys(templatesMap).length > 0) {
                rendered = wasm.render_entry_with_templates(
                    entryHtml,
                    JSON.stringify(templatesMap),
                    JSON.stringify(state),
                );
            } else {
                rendered = wasm.render(entryHtml, JSON.stringify(state));
            }

            // Extract the body content from the rendered document.
            const bodyMatch = rendered.match(/<body[^>]*>([\s\S]*)<\/body>/i);
            const fixture = bodyMatch?.[1]?.trim() ?? rendered;

            return {
                fixture,
                template: templateEntries,
                preloadLinks: "",
            };
        },
    };
}
