name: Release packages to GitHub releases

on:
  workflow_dispatch:
  schedule:
  - cron: '0 8 * * *' # Midnight PST = 08:00 UTC.

env:
  GITHUB_SERVICE_USER: "Microsoft FAST Builds"
  GITHUB_SERVICE_EMAIL: "fastsvc@microsoft.com"

permissions: { contents: write }

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_TOKEN }}

    - uses: actions/setup-node@v6
      with:
        node-version: 22

    - name: Set Git User
      run: |
        git config --global user.name "${{ env.GITHUB_SERVICE_USER }}"
        git config --global user.email "${{ env.GITHUB_SERVICE_EMAIL }}"

    - name: Cache multiple paths
      uses: actions/cache@v4
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install package dependencies
      run: npm ci

    - name: Install Rust and wasm-pack
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
        export PATH="$HOME/.cargo/bin:$PATH"
        rustup target add wasm32-unknown-unknown
        cargo install wasm-pack
        echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"

    - name: Build workspaces
      run: npm run build

    - name: Bump versions and pack tarballs
      run: npm run publish-ci
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Create GitHub releases for new package versions
      run: node build/scripts/create-github-releases.mjs
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
