name: Validate Rust crates

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - releases/*
  pull_request:
    branches:
    - main
    - releases/*
    - features/*
    types:
    - opened
    - synchronize
    - reopened
    - ready_for_review

jobs:
  test_rust:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0

    - name: Install Rust stable toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Run Rust microsoft-fast-build tests
      run: cargo test --manifest-path crates/microsoft-fast-build/Cargo.toml

    - name: Run Rust microsoft-fast-build tests
      run: cargo test --manifest-path crates/microsoft-fast-convert/Cargo.toml
