name: WebUI Integration Tests

on:
  workflow_dispatch:
  push:
    branches:
    - webui/*

permissions:
  contents: read

jobs:
  webui_integration:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      with:
        fetch-depth: 0

    - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
      with:
        node-version: 22

    - name: Cache npm modules
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install package dependencies
      run: npm ci

    - name: Install wasm-pack
      run: cargo install wasm-pack

    - name: Build workspaces
      run: npm run build -- --verbose

    - name: Install Playwright browsers
      run: npx playwright install --with-deps chromium

    - name: Run WebUI integration tests
      run: npm run test:webui-integration -w @microsoft/fast-element
